### ISSUE TITLE
Welcome back to Angular Starter

### ISSUE THREAD

**Issue by PatrickJS** [PatrickJS/PatrickJS-starter#2068]
Hey ✌️
I'm in the middle of redoing everything to be Microfrontends focus which will allow you to work in Angular, Qwik, and React (and even angular.js and vue). The repo will support the full stack of a web app: static/dynamic/design-system/deployment/development/production from "hello world" to enterprise-grade

new repo focus:
* browser: evergreen only (no ie 11)
* browser: Legacy browsers can still be supported
* webpack: Webpack 5+ only
* webpack: Webpack Module Federation support
* webpack: Easy way to configure/manage all webpack configurations
* angular: Better Angular experience than Angular CLI
* angular: Reuse Services between each frameworks with no code cost
* angular: Angular Elements/Standalone only
* angular: Never have to write NgModule or Router config (unless you want/need to)
* react: be able to reuse angular di system without breaking the react-way of doing things
* components: Easy way to integrate to your Design-Systems (whatever it is: bootstrap, material, custom)
* components: [Mitosis](https://github.com/BuilderIO/mitosis) integration for your Design-Systems
* api: Easy integration to use GraphQL, REST, tRPC
* docker: Optional Docker support
* deno: Optional Deno.js support

Please feel free to ask any questions here and follow this issue for more repo updates in the coming months 👍

If you're looking for angular starters please use the ones others have listed in comments below

**Comment by kamil-kielczewski** [comment]
It looks like this project is DEAD

**Comment by wlucha** [comment]
Since there hasn't been any updates on this project for a long time:

I created an **Angular starter project based on Angular 13**:
**https://github.com/wlucha/angular-starter**

**Comment by kasparov112000** [comment]
Fixed the webpack issues and updated to ng 13 on my branch https://github.com/kasparov112000/angular-ngrx-material-starter

**Comment by PatrickJS** [comment]
I'm redoing the whole repo to be microfrontends starter which will allow you to work on ngx/react apps and reuse services between the two apps and never have to write NgModule or router config. If you want an angular starter please use the ones suggested in this thread

**Comment by PatrickJS** [comment]
updates:

* adding a new requirement for angular. Angular Elements only.
* adding deno
* adding tRPC as an option

**Comment by PatrickJS** [comment]
There is a high chance I'm going to ditch the angular/react router

**Comment by PatrickJS** [comment]
I figured out how to support any angular: ng13, ng14 standalone, ng elements

**Comment by PatrickJS** [comment]
ok I actually built the react+angular thing but I didn't like it because it turned into it's own framework and I didn't want that. I also didn't like all the MFE issues. So this repo will be qwik only going forward. Since the starter repo has always been my opinions on how things should work this is the simplest architecture
